#!/bin/bash

# Path
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

if [ "`uname -s`" == "Darwin" ]; then
	export HOME_PREFIX=`brew --prefix`
else
	export HOME_PREFIX=
fi

export PATH="$HOME/bin:$HOME_PREFIX/bin:$HOME_PREFIX/sbin"

# Editor
export EDITOR="subl -w"
