#!/bin/bash

# Path
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin

if [ "`uname -s`" = "Darwin" ]; then
	# homebrew on Apple M1 is in /opt/homebrew
    export PATH=$PATH:/opt/homebrew/bin
	export HOME_PREFIX=`brew --prefix`
	# set ruby gem home
	export PATH=$PATH:`brew info ruby|grep /bin|tr -d ' '`
elif [[ `uname -s` = Linux ]]; then
    export PATH=$PATH
fi

export PATH="$HOME/bin:$HOME_PREFIX/bin:$HOME_PREFIX/sbin:$PATH"

# Editor
export EDITOR="code --wait"
