#!/bin/bash

# only interactive shells
[[ "$-" != *i* ]] && return

# See http://www.shellperson.net/using-sudo-with-an-alias/
alias sudo='sudo '

alias ~="cd ~"
alias ..="cd .."

alias reload=". ~/.profile"

if [ "`uname -s`" == "Darwin" ]; then
	alias l='ls -hlG'
	alias ls='ls -hF'
	alias ll='ls -halG'
	alias la='ls -A'
else
	alias l='ls -hlG --color=auto'
	alias ls='ls -hF --color=auto'
	alias ll='ls -halG --color=auto'
	alias la='ls -A --color=auto'
fi

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rgrep='egrep -R --color=auto'

alias e="subl"
alias rrsync='rsync -avz --delete --exclude=".svn" '
alias pstree='\ps auxwwwf'

# prevent accidental operations
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'

# symform related aliases
alias xb='MONO_IOMAP=case xbuild'
alias sym="cd ~/symform"
