#!/bin/bash

if [ "`uname -s`" == "Linux" ]; then
	if ! which ccache > /dev/null; then
		echo installing ccache
		sudo apt-get install ccache
	fi
	export CCACHE_DIR="${HOME}/.ccache"
	cat <<EOF > ~/.ccache/ccache.conf
max_size = 10G
EOF
fi

