#!/bin/bash

if which git &>/dev/null; then
	git config --global user.email "bassam.tabbara@quantum.com"
	git config --global user.name "Bassam Tabbara"
	git config --global push.default simple
	git config --global color.ui true
fi

# git related aliases
alias gitsub="git submodule update --init --recursive"
alias gitf="git fetch --all --prune"
