#!/bin/bash -e

if which git &>/dev/null; then
	rm -fr ~/.gitconfig

	git config --global user.email "bassam@tabbara.com"
	git config --global user.name "Bassam Tabbara"
	git config --global push.default simple
	git config --global color.ui true

	git config --global diff.tool "code --wait --diff \$LOCAL \$REMOTE"
	git config --global difftool.prompt false
fi

# git related aliases
alias gitsub="git submodule update --init --recursive"
alias gitf="git fetch --all --prune"

# set the git prompt
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
	__GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
	source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi

# set the global .gitignore
cat <<EOF > ~/.gitignore
.DS_Store
.vscode/
EOF
