#!/bin/bash

export GO15VENDOREXPERIMENT=1
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

token=$(cat ~/.secrets/github/token)
cat > ~/.netrc <<EOF
machine github.com
  login bassamtabbara
  password ${token}
EOF
