#!/bin/bash

return

# only interactive shells
[[ "$-" != *i* ]] && return

# #######################
# Key bindings
# #######################

# Ctrl+Left/Right to move by whole words
bind '"\e[1;5D": backward-word'
bind '"\e[1;5C": forward-word'

# Ctrl+Up/Down to move to beginning and end of line
bind '"\e[1;5A": beginning-of-line'
bind '"\e[1;5B": end-of-line'

# Tab for menu-complete, CTRL-TAB for complete, CTRL-Space to list completions
bind '"\t": complete'
bind '"\e[Z": menu-complete'
bind '"\C- ":possible-completions'

# Ctrl+Backspace/Delete to delete whole words
bind '"\e[3;5~": kill-word'
bind '"\C-_": backward-kill-word'

# Ctrl+Shift+Backspace/Delete to delete to start/end of the line
bind '"\e[3;6~": kill-line'
bind '"\xC2\x9F": backward-kill-line'  # for UTF-8

# Alt-Backspace for undo
bind '"\e\d": undo'

# #######################
# Terminal
# #######################

# Unix terminal line drivers have a flow control feature that allow terminal output to be stopped with Ctrl+S and restarted with Ctrl+Q. 
# However, due to the scrollback feature in modern terminal emulators, there is little need for this. 
# Hence, to make those key combinations available for other uses, disable flow control with this command:
stty -ixon