#!/bin/bash

# only interactive shells
[[ "$-" != *i* ]] && return

# see http://mywiki.wooledge.org/BashFAQ/053

# colors
BLACK="$(tput setaf 0)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
PURPLE="$(tput setaf 5)"
CYAN="$(tput setaf 6)"
WHITE="$(tput setaf 7)"

# colors
BLACK_B="$(tput setab 0)"
RED_B="$(tput setab 1)"
GREEN_B="$(tput setab 2)"
YELLOW_B="$(tput setab 3)"
BLUE_B="$(tput setab 4)"
PURPLE_B="$(tput setab 5)"
CYAN_B="$(tput setab 6)"
WHITE_B="$(tput setab 7)"

DEFAULT="$(tput sgr0)"

function parse_git_branch {
    ref=$(git branch 2>/dev/null|grep \*|sed 's/* //') || return
    if [ "$ref" != "" ]
    then
        echo " ("${ref}")"
    fi
}

function lastcommandfailed() {
  code=$?
  if [ $code != 0 ]; then
    echo -n "[$code] "
  fi
}

PROMPT="\[${RED_B}\]\[${YELLOW}\]\$(lastcommandfailed)\[${DEFAULT}\]\[${YELLOW}\]\u\[${GREEN}\]@\h\[${CYAN}\] \[${PURPLE}\]\[${YELLOW}\]\w\[\$(parse_git_branch)\]\n\[${YELLOW}\]> \[${DEFAULT}\]"
export PS1=$PROMPT

