#!/bin/bash

# only interactive shells
[[ "$-" != *i* ]] && return

# #######################
# Shell Options
# #######################

# If set, bash matches filenames in a case-insensitive fashion when performing pathname expansion  (see  Pathname  Expansion above).
shopt -s nocaseglob

# Don't use ^D to exit
set -o ignoreeof

# Use case-insensitive filename globbing
set completion-ignore-case on

# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find /var/log/apache
shopt -s cdspell

# If set, bash checks the window size after each command and, if necessary, updates the values of LINES and COLUMNS.
shopt -s checkwinsize

# #######################
# Completion options
# #######################

# If this shell is interactive, turn on programmable completion enhancements.
# Any completions you add in ~/.bash_completion are sourced last.
[[ -f $HOME_PREFIX/etc/bash_completion ]] && . $HOME_PREFIX/etc/bash_completion

# #######################
# History Options
# #######################

# Make bash append rather than overwrite the history on disk
shopt -s histappend

# Don't put duplicate lines in the history.
export HISTCONTROL="ignoredups"

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
export HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=1000
export HISTFILESIZE=2000

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# Ignore some controlling instructions
# HISTIGNORE is a colon-delimited list of patterns which should be excluded.
# The '&' is a special pattern which suppresses duplicate entries.
export HISTIGNORE=$'[ \t]*:&:[fb]g:exit:ls' # Ignore the ls command as well

# Whenever displaying the prompt, write the previous line to disk
# export PROMPT_COMMAND="history -a; history -n"
