#!/bin/bash -e

if [[ `uname -s` == "Linux" ]]; then
	if [[ ! -d /usr/local/VSCode-linux-x64 ]]; then
		echo installing VS Code
		version=0.10.6
		wget https://az764295.vo.msecnd.net/public/${version}-release/VSCode-linux64.zip -O /tmp/VSCode-linux64.zip
		sudo unzip /tmp/VSCode-linux64.zip -d /usr/local/
		sudo sysctl -w fs.inotify.max_user_watches=16384
	fi
fi

